# Generated by Django 3.1.7 on 2021-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_hour', models.CharField(max_length=6)),
                ('second_hour', models.CharField(max_length=6)),
                ('third_hour', models.CharField(max_length=6)),
                ('fourth_hour', models.CharField(max_length=6)),
                ('fifth_hour', models.CharField(max_length=6)),
                ('sixth_hour', models.CharField(max_length=6)),
                ('seventh_hour', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('parent_phone', models.IntegerField()),
                ('compiler_design', models.IntegerField()),
                ('unix_programming', models.IntegerField()),
                ('ooad', models.IntegerField()),
                ('dbms', models.IntegerField()),
                ('os', models.IntegerField()),
                ('os_lp_lab', models.IntegerField()),
                ('dbms_lab', models.IntegerField()),
                ('ooad_lab', models.IntegerField()),
            ],
        ),
    ]
