# Generated by Django 3.1.8 on 2021-04-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_student_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_attendance',
        ),
    ]
