# Generated by Django 3.1.8 on 2021-04-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_delete_student_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_attendance',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('parent_phone', models.CharField(max_length=13)),
                ('first_hour', models.CharField(max_length=6)),
                ('second_hour', models.CharField(max_length=6)),
                ('third_hour', models.CharField(max_length=6)),
                ('fourth_hour', models.CharField(max_length=6)),
                ('fifth_hour', models.CharField(max_length=6)),
                ('sixth_hour', models.CharField(max_length=6)),
                ('seventh_hour', models.CharField(max_length=6)),
                ('total_attendace', models.IntegerField()),
            ],
        ),
    ]
