# Generated by Django 3.1.8 on 2021-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_delete_student_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('student_year', models.IntegerField()),
                ('parent_phone', models.CharField(max_length=13)),
                ('compiler_design', models.IntegerField()),
                ('unix_programming', models.IntegerField()),
                ('ooad', models.IntegerField()),
                ('dbms', models.IntegerField()),
                ('os', models.IntegerField()),
                ('os_lp_lab', models.IntegerField()),
                ('dbms_lab', models.IntegerField()),
                ('ooad_lab', models.IntegerField()),
            ],
        ),
    ]
